import type { Food } from "./types";
import { CATALOG_SEED_FOODS } from "./seed-foods-catalog";
import { BULGARIAN_SEED_FOODS } from "./seed-foods-bulgarian";
import { STAPLE_SEED_FOODS } from "./seed-foods-staples";

type SeedFood = Omit<Food, "id">;

const BASE_SEED_FOODS: SeedFood[] = [
  {
    name: "Egg (large)",
    serving_size: 1,
    serving_unit: "egg",
    calories: 72,
    protein_g: 6.3,
    carbs_g: 0.4,
    fat_g: 4.8,
    fiber_g: 0,
    sugar_g: 0.2,
    sodium_mg: 71,
    vitamin_a_mcg: 80,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 1.1,
    vitamin_b12_mcg: 0.6,
    iron_mg: 0.9,
    calcium_mg: 28,
    potassium_mg: 69,
  },
  {
    name: "Chicken breast (grilled)",
    serving_size: 100,
    serving_unit: "g",
    calories: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 74,
    vitamin_a_mcg: 9,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.3,
    iron_mg: 1,
    calcium_mg: 15,
    potassium_mg: 256,
  },
  {
    name: "Greek yogurt (plain, nonfat)",
    serving_size: 170,
    serving_unit: "g",
    calories: 100,
    protein_g: 17,
    carbs_g: 6,
    fat_g: 0.7,
    fiber_g: 0,
    sugar_g: 6,
    sodium_mg: 61,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 1.2,
    iron_mg: 0.1,
    calcium_mg: 187,
    potassium_mg: 240,
  },
  {
    name: "Oatmeal (cooked)",
    serving_size: 234,
    serving_unit: "g",
    calories: 158,
    protein_g: 6,
    carbs_g: 27,
    fat_g: 3.2,
    fiber_g: 4,
    sugar_g: 1.1,
    sodium_mg: 115,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 2.1,
    calcium_mg: 21,
    potassium_mg: 164,
  },
  {
    name: "Banana (medium)",
    serving_size: 1,
    serving_unit: "banana",
    calories: 105,
    protein_g: 1.3,
    carbs_g: 27,
    fat_g: 0.4,
    fiber_g: 3.1,
    sugar_g: 14,
    sodium_mg: 1,
    vitamin_a_mcg: 4,
    vitamin_c_mg: 10,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.3,
    calcium_mg: 6,
    potassium_mg: 422,
  },
  {
    name: "Salmon (baked)",
    serving_size: 100,
    serving_unit: "g",
    calories: 208,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 59,
    vitamin_a_mcg: 12,
    vitamin_c_mg: 3.9,
    vitamin_d_mcg: 11,
    vitamin_b12_mcg: 3.2,
    iron_mg: 0.3,
    calcium_mg: 9,
    potassium_mg: 363,
  },
  {
    name: "Brown rice (cooked)",
    serving_size: 195,
    serving_unit: "g",
    calories: 216,
    protein_g: 5,
    carbs_g: 45,
    fat_g: 1.8,
    fiber_g: 3.5,
    sugar_g: 0.7,
    sodium_mg: 10,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 20,
    potassium_mg: 84,
  },
  {
    name: "Broccoli (steamed)",
    serving_size: 156,
    serving_unit: "g",
    calories: 55,
    protein_g: 3.7,
    carbs_g: 11,
    fat_g: 0.6,
    fiber_g: 5.1,
    sugar_g: 2.2,
    sodium_mg: 64,
    vitamin_a_mcg: 120,
    vitamin_c_mg: 101,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1,
    calcium_mg: 62,
    potassium_mg: 457,
  },
  {
    name: "Almonds",
    serving_size: 28,
    serving_unit: "g",
    calories: 164,
    protein_g: 6,
    carbs_g: 6,
    fat_g: 14,
    fiber_g: 3.5,
    sugar_g: 1.2,
    sodium_mg: 0,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1,
    calcium_mg: 76,
    potassium_mg: 208,
  },
  {
    name: "Whole wheat bread",
    serving_size: 1,
    serving_unit: "slice",
    calories: 81,
    protein_g: 4,
    carbs_g: 14,
    fat_g: 1.1,
    fiber_g: 1.9,
    sugar_g: 1.4,
    sodium_mg: 144,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.9,
    calcium_mg: 40,
    potassium_mg: 69,
  },
  {
    name: "Avocado (half)",
    serving_size: 1,
    serving_unit: "half",
    calories: 161,
    protein_g: 2,
    carbs_g: 8.5,
    fat_g: 14.7,
    fiber_g: 6.7,
    sugar_g: 0.7,
    sodium_mg: 7,
    vitamin_a_mcg: 7,
    vitamin_c_mg: 10,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.6,
    calcium_mg: 12,
    potassium_mg: 487,
  },
  {
    name: "Milk (2%)",
    serving_size: 244,
    serving_unit: "ml",
    calories: 122,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 4.8,
    fiber_g: 0,
    sugar_g: 12,
    sodium_mg: 115,
    vitamin_a_mcg: 68,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 2.9,
    vitamin_b12_mcg: 1.3,
    iron_mg: 0.1,
    calcium_mg: 293,
    potassium_mg: 342,
  },
  {
    name: "Spinach (raw)",
    serving_size: 30,
    serving_unit: "g",
    calories: 7,
    protein_g: 0.9,
    carbs_g: 1.1,
    fat_g: 0.1,
    fiber_g: 0.7,
    sugar_g: 0.1,
    sodium_mg: 24,
    vitamin_a_mcg: 141,
    vitamin_c_mg: 8.4,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 30,
    potassium_mg: 167,
  },
  {
    name: "Apple (medium)",
    serving_size: 1,
    serving_unit: "apple",
    calories: 95,
    protein_g: 0.5,
    carbs_g: 25,
    fat_g: 0.3,
    fiber_g: 4.4,
    sugar_g: 19,
    sodium_mg: 2,
    vitamin_a_mcg: 5,
    vitamin_c_mg: 8.4,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 11,
    potassium_mg: 195,
  },
  {
    name: "Whey protein shake",
    serving_size: 1,
    serving_unit: "scoop",
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1.5,
    fiber_g: 0,
    sugar_g: 2,
    sodium_mg: 130,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0,
    calcium_mg: 120,
    potassium_mg: 160,
  },
  // Dairy & milk
  {
    name: "Milk (whole)",
    serving_size: 244,
    serving_unit: "ml",
    calories: 149,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 8,
    fiber_g: 0,
    sugar_g: 12,
    sodium_mg: 105,
    vitamin_a_mcg: 68,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 2.9,
    vitamin_b12_mcg: 1.1,
    iron_mg: 0.1,
    calcium_mg: 276,
    potassium_mg: 322,
  },
  {
    name: "Milk (skim)",
    serving_size: 244,
    serving_unit: "ml",
    calories: 83,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 0.2,
    fiber_g: 0,
    sugar_g: 12,
    sodium_mg: 103,
    vitamin_a_mcg: 68,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 2.9,
    vitamin_b12_mcg: 1.2,
    iron_mg: 0.1,
    calcium_mg: 299,
    potassium_mg: 382,
  },
  {
    name: "Milk (semi-skimmed)",
    serving_size: 244,
    serving_unit: "ml",
    calories: 122,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 4.8,
    fiber_g: 0,
    sugar_g: 12,
    sodium_mg: 115,
    vitamin_a_mcg: 68,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 2.9,
    vitamin_b12_mcg: 1.3,
    iron_mg: 0.1,
    calcium_mg: 293,
    potassium_mg: 342,
  },
  {
    name: "Oat milk",
    serving_size: 240,
    serving_unit: "ml",
    calories: 120,
    protein_g: 3,
    carbs_g: 16,
    fat_g: 5,
    fiber_g: 2,
    sugar_g: 7,
    sodium_mg: 100,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 3.6,
    vitamin_b12_mcg: 1.2,
    iron_mg: 0.3,
    calcium_mg: 350,
    potassium_mg: 350,
  },
  {
    name: "Almond milk (unsweetened)",
    serving_size: 240,
    serving_unit: "ml",
    calories: 30,
    protein_g: 1,
    carbs_g: 1,
    fat_g: 2.5,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 170,
    vitamin_a_mcg: 150,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 2.4,
    vitamin_b12_mcg: 0.9,
    iron_mg: 0.4,
    calcium_mg: 450,
    potassium_mg: 160,
  },
  {
    name: "Cheddar cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 113,
    protein_g: 7,
    carbs_g: 0.4,
    fat_g: 9,
    fiber_g: 0,
    sugar_g: 0.1,
    sodium_mg: 174,
    vitamin_a_mcg: 75,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.2,
    iron_mg: 0.2,
    calcium_mg: 202,
    potassium_mg: 28,
  },
  {
    name: "Mozzarella cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 85,
    protein_g: 6,
    carbs_g: 0.7,
    fat_g: 6,
    fiber_g: 0,
    sugar_g: 0.3,
    sodium_mg: 138,
    vitamin_a_mcg: 44,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.4,
    iron_mg: 0.1,
    calcium_mg: 143,
    potassium_mg: 19,
  },
  {
    name: "Feta cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 74,
    protein_g: 4,
    carbs_g: 1.2,
    fat_g: 6,
    fiber_g: 0,
    sugar_g: 1.2,
    sodium_mg: 316,
    vitamin_a_mcg: 35,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.4,
    iron_mg: 0.2,
    calcium_mg: 140,
    potassium_mg: 18,
  },
  {
    name: "Parmesan cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 111,
    protein_g: 10,
    carbs_g: 0.9,
    fat_g: 7,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 449,
    vitamin_a_mcg: 48,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.2,
    vitamin_b12_mcg: 0.3,
    iron_mg: 0.2,
    calcium_mg: 314,
    potassium_mg: 26,
  },
  {
    name: "Cottage cheese (low fat)",
    serving_size: 113,
    serving_unit: "g",
    calories: 92,
    protein_g: 12,
    carbs_g: 5,
    fat_g: 2.5,
    fiber_g: 0,
    sugar_g: 4,
    sodium_mg: 406,
    vitamin_a_mcg: 37,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.6,
    iron_mg: 0.1,
    calcium_mg: 103,
    potassium_mg: 125,
  },
  {
    name: "Cream cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 99,
    protein_g: 2,
    carbs_g: 1,
    fat_g: 10,
    fiber_g: 0,
    sugar_g: 1,
    sodium_mg: 91,
    vitamin_a_mcg: 98,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.1,
    iron_mg: 0.1,
    calcium_mg: 28,
    potassium_mg: 39,
  },
  {
    name: "Brie cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 95,
    protein_g: 6,
    carbs_g: 0.1,
    fat_g: 8,
    fiber_g: 0,
    sugar_g: 0.1,
    sodium_mg: 178,
    vitamin_a_mcg: 60,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.4,
    iron_mg: 0.2,
    calcium_mg: 52,
    potassium_mg: 28,
  },
  {
    name: "Goat cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 75,
    protein_g: 5,
    carbs_g: 0.3,
    fat_g: 6,
    fiber_g: 0,
    sugar_g: 0.3,
    sodium_mg: 130,
    vitamin_a_mcg: 76,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.1,
    iron_mg: 0.3,
    calcium_mg: 40,
    potassium_mg: 7,
  },
  {
    name: "Swiss cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 106,
    protein_g: 8,
    carbs_g: 1.5,
    fat_g: 8,
    fiber_g: 0,
    sugar_g: 0.5,
    sodium_mg: 54,
    vitamin_a_mcg: 67,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.7,
    iron_mg: 0.1,
    calcium_mg: 252,
    potassium_mg: 22,
  },
  {
    name: "Blue cheese",
    serving_size: 28,
    serving_unit: "g",
    calories: 100,
    protein_g: 6,
    carbs_g: 0.7,
    fat_g: 8,
    fiber_g: 0,
    sugar_g: 0.1,
    sodium_mg: 325,
    vitamin_a_mcg: 56,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.3,
    iron_mg: 0.1,
    calcium_mg: 150,
    potassium_mg: 53,
  },
  // Proteins
  {
    name: "Beef mince (lean, cooked)",
    serving_size: 100,
    serving_unit: "g",
    calories: 250,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 15,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 72,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 2.6,
    iron_mg: 2.6,
    calcium_mg: 18,
    potassium_mg: 318,
  },
  {
    name: "Turkey breast (roasted)",
    serving_size: 100,
    serving_unit: "g",
    calories: 135,
    protein_g: 30,
    carbs_g: 0,
    fat_g: 1,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 59,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0.3,
    iron_mg: 0.7,
    calcium_mg: 13,
    potassium_mg: 249,
  },
  {
    name: "Tuna (canned in water)",
    serving_size: 85,
    serving_unit: "g",
    calories: 73,
    protein_g: 16,
    carbs_g: 0,
    fat_g: 0.8,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 210,
    vitamin_a_mcg: 12,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 1.5,
    vitamin_b12_mcg: 2.2,
    iron_mg: 1.2,
    calcium_mg: 10,
    potassium_mg: 153,
  },
  {
    name: "Prawns (shrimp, cooked)",
    serving_size: 100,
    serving_unit: "g",
    calories: 99,
    protein_g: 24,
    carbs_g: 0.2,
    fat_g: 0.3,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 111,
    vitamin_a_mcg: 54,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 1.4,
    iron_mg: 0.5,
    calcium_mg: 70,
    potassium_mg: 259,
  },
  {
    name: "Tofu (firm)",
    serving_size: 126,
    serving_unit: "g",
    calories: 94,
    protein_g: 10,
    carbs_g: 2,
    fat_g: 6,
    fiber_g: 0.5,
    sugar_g: 0.5,
    sodium_mg: 9,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.8,
    calcium_mg: 253,
    potassium_mg: 150,
  },
  // Carbs & staples
  {
    name: "Pasta (cooked)",
    serving_size: 140,
    serving_unit: "g",
    calories: 220,
    protein_g: 8,
    carbs_g: 43,
    fat_g: 1,
    fiber_g: 2.5,
    sugar_g: 0.8,
    sodium_mg: 1,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.8,
    calcium_mg: 10,
    potassium_mg: 62,
  },
  {
    name: "White rice (cooked)",
    serving_size: 158,
    serving_unit: "g",
    calories: 205,
    protein_g: 4,
    carbs_g: 45,
    fat_g: 0.4,
    fiber_g: 0.6,
    sugar_g: 0.1,
    sodium_mg: 2,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.3,
    calcium_mg: 16,
    potassium_mg: 55,
  },
  {
    name: "Potato (baked, medium)",
    serving_size: 1,
    serving_unit: "potato",
    calories: 161,
    protein_g: 4,
    carbs_g: 37,
    fat_g: 0.2,
    fiber_g: 3.8,
    sugar_g: 1.9,
    sodium_mg: 17,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 17,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.9,
    calcium_mg: 26,
    potassium_mg: 897,
  },
  {
    name: "Sweet potato (medium, baked)",
    serving_size: 1,
    serving_unit: "potato",
    calories: 103,
    protein_g: 2,
    carbs_g: 24,
    fat_g: 0.1,
    fiber_g: 3.8,
    sugar_g: 7,
    sodium_mg: 41,
    vitamin_a_mcg: 922,
    vitamin_c_mg: 22,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.7,
    calcium_mg: 43,
    potassium_mg: 542,
  },
  {
    name: "Quinoa (cooked)",
    serving_size: 185,
    serving_unit: "g",
    calories: 222,
    protein_g: 8,
    carbs_g: 39,
    fat_g: 4,
    fiber_g: 5,
    sugar_g: 1.6,
    sodium_mg: 13,
    vitamin_a_mcg: 5,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 2.8,
    calcium_mg: 31,
    potassium_mg: 318,
  },
  // Fruits & veg
  {
    name: "Orange (medium)",
    serving_size: 1,
    serving_unit: "orange",
    calories: 62,
    protein_g: 1,
    carbs_g: 15,
    fat_g: 0.2,
    fiber_g: 3.1,
    sugar_g: 12,
    sodium_mg: 0,
    vitamin_a_mcg: 14,
    vitamin_c_mg: 70,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.1,
    calcium_mg: 52,
    potassium_mg: 237,
  },
  {
    name: "Blueberries",
    serving_size: 148,
    serving_unit: "g",
    calories: 84,
    protein_g: 1,
    carbs_g: 21,
    fat_g: 0.5,
    fiber_g: 3.6,
    sugar_g: 15,
    sodium_mg: 1,
    vitamin_a_mcg: 4,
    vitamin_c_mg: 14,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.4,
    calcium_mg: 9,
    potassium_mg: 114,
  },
  {
    name: "Strawberries",
    serving_size: 152,
    serving_unit: "g",
    calories: 49,
    protein_g: 1,
    carbs_g: 12,
    fat_g: 0.5,
    fiber_g: 3,
    sugar_g: 7,
    sodium_mg: 2,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 89,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.6,
    calcium_mg: 24,
    potassium_mg: 233,
  },
  {
    name: "Tomato (medium)",
    serving_size: 1,
    serving_unit: "tomato",
    calories: 22,
    protein_g: 1,
    carbs_g: 5,
    fat_g: 0.2,
    fiber_g: 1.5,
    sugar_g: 3,
    sodium_mg: 6,
    vitamin_a_mcg: 51,
    vitamin_c_mg: 17,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.3,
    calcium_mg: 12,
    potassium_mg: 292,
  },
  {
    name: "Carrot (medium, raw)",
    serving_size: 1,
    serving_unit: "carrot",
    calories: 25,
    protein_g: 0.6,
    carbs_g: 6,
    fat_g: 0.1,
    fiber_g: 1.7,
    sugar_g: 3,
    sodium_mg: 42,
    vitamin_a_mcg: 509,
    vitamin_c_mg: 4,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 20,
    potassium_mg: 195,
  },
  {
    name: "Bell pepper (red, medium)",
    serving_size: 1,
    serving_unit: "pepper",
    calories: 37,
    protein_g: 1,
    carbs_g: 7,
    fat_g: 0.3,
    fiber_g: 2.5,
    sugar_g: 5,
    sodium_mg: 5,
    vitamin_a_mcg: 187,
    vitamin_c_mg: 152,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.5,
    calcium_mg: 8,
    potassium_mg: 251,
  },
  {
    name: "Watermelon",
    serving_size: 280,
    serving_unit: "g",
    calories: 85,
    protein_g: 1.7,
    carbs_g: 21,
    fat_g: 0.4,
    fiber_g: 1.1,
    sugar_g: 18,
    sodium_mg: 3,
    vitamin_a_mcg: 64,
    vitamin_c_mg: 23,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.7,
    calcium_mg: 20,
    potassium_mg: 314,
  },
  {
    name: "Cantaloupe melon",
    serving_size: 177,
    serving_unit: "g",
    calories: 60,
    protein_g: 1.5,
    carbs_g: 14,
    fat_g: 0.3,
    fiber_g: 1.6,
    sugar_g: 14,
    sodium_mg: 28,
    vitamin_a_mcg: 270,
    vitamin_c_mg: 65,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.4,
    calcium_mg: 16,
    potassium_mg: 427,
  },
  {
    name: "Honeydew melon",
    serving_size: 170,
    serving_unit: "g",
    calories: 61,
    protein_g: 0.9,
    carbs_g: 15,
    fat_g: 0.2,
    fiber_g: 1.4,
    sugar_g: 14,
    sodium_mg: 30,
    vitamin_a_mcg: 3,
    vitamin_c_mg: 31,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 10,
    potassium_mg: 276,
  },
  {
    name: "Grapes",
    serving_size: 151,
    serving_unit: "g",
    calories: 104,
    protein_g: 1,
    carbs_g: 27,
    fat_g: 0.2,
    fiber_g: 1.4,
    sugar_g: 23,
    sodium_mg: 3,
    vitamin_a_mcg: 5,
    vitamin_c_mg: 4,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.5,
    calcium_mg: 15,
    potassium_mg: 288,
  },
  {
    name: "Mango",
    serving_size: 165,
    serving_unit: "g",
    calories: 99,
    protein_g: 1.4,
    carbs_g: 25,
    fat_g: 0.6,
    fiber_g: 2.6,
    sugar_g: 23,
    sodium_mg: 2,
    vitamin_a_mcg: 89,
    vitamin_c_mg: 60,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.3,
    calcium_mg: 18,
    potassium_mg: 277,
  },
  {
    name: "Pineapple",
    serving_size: 165,
    serving_unit: "g",
    calories: 82,
    protein_g: 0.9,
    carbs_g: 22,
    fat_g: 0.2,
    fiber_g: 2.3,
    sugar_g: 16,
    sodium_mg: 2,
    vitamin_a_mcg: 4,
    vitamin_c_mg: 79,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.5,
    calcium_mg: 21,
    potassium_mg: 180,
  },
  {
    name: "Kiwi",
    serving_size: 1,
    serving_unit: "kiwi",
    calories: 42,
    protein_g: 0.8,
    carbs_g: 10,
    fat_g: 0.4,
    fiber_g: 2.1,
    sugar_g: 6,
    sodium_mg: 2,
    vitamin_a_mcg: 3,
    vitamin_c_mg: 64,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 23,
    potassium_mg: 215,
  },
  {
    name: "Peach (medium)",
    serving_size: 1,
    serving_unit: "peach",
    calories: 59,
    protein_g: 1.4,
    carbs_g: 14,
    fat_g: 0.4,
    fiber_g: 2.3,
    sugar_g: 13,
    sodium_mg: 0,
    vitamin_a_mcg: 24,
    vitamin_c_mg: 10,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.4,
    calcium_mg: 9,
    potassium_mg: 285,
  },
  {
    name: "Pear (medium)",
    serving_size: 1,
    serving_unit: "pear",
    calories: 101,
    protein_g: 0.6,
    carbs_g: 27,
    fat_g: 0.2,
    fiber_g: 5.5,
    sugar_g: 17,
    sodium_mg: 2,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 8,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 16,
    potassium_mg: 206,
  },
  {
    name: "Raspberries",
    serving_size: 123,
    serving_unit: "g",
    calories: 64,
    protein_g: 1.5,
    carbs_g: 15,
    fat_g: 0.8,
    fiber_g: 8,
    sugar_g: 5,
    sodium_mg: 1,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 32,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 31,
    potassium_mg: 186,
  },
  {
    name: "Cherries",
    serving_size: 138,
    serving_unit: "g",
    calories: 87,
    protein_g: 1.5,
    carbs_g: 22,
    fat_g: 0.3,
    fiber_g: 2.9,
    sugar_g: 18,
    sodium_mg: 0,
    vitamin_a_mcg: 3,
    vitamin_c_mg: 10,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.5,
    calcium_mg: 18,
    potassium_mg: 306,
  },
  {
    name: "Grapefruit (half)",
    serving_size: 1,
    serving_unit: "half",
    calories: 52,
    protein_g: 0.9,
    carbs_g: 13,
    fat_g: 0.2,
    fiber_g: 2,
    sugar_g: 8,
    sodium_mg: 0,
    vitamin_a_mcg: 71,
    vitamin_c_mg: 44,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.1,
    calcium_mg: 27,
    potassium_mg: 166,
  },
  {
    name: "Plum (medium)",
    serving_size: 1,
    serving_unit: "plum",
    calories: 30,
    protein_g: 0.5,
    carbs_g: 8,
    fat_g: 0.2,
    fiber_g: 0.9,
    sugar_g: 7,
    sodium_mg: 0,
    vitamin_a_mcg: 17,
    vitamin_c_mg: 7,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.1,
    calcium_mg: 4,
    potassium_mg: 104,
  },
  {
    name: "Cucumber (medium)",
    serving_size: 1,
    serving_unit: "cucumber",
    calories: 45,
    protein_g: 2,
    carbs_g: 11,
    fat_g: 0.3,
    fiber_g: 1.5,
    sugar_g: 5,
    sodium_mg: 6,
    vitamin_a_mcg: 10,
    vitamin_c_mg: 8,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 48,
    potassium_mg: 442,
  },
  {
    name: "Zucchini (medium)",
    serving_size: 1,
    serving_unit: "zucchini",
    calories: 33,
    protein_g: 2.4,
    carbs_g: 6,
    fat_g: 0.6,
    fiber_g: 2,
    sugar_g: 5,
    sodium_mg: 13,
    vitamin_a_mcg: 40,
    vitamin_c_mg: 35,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 31,
    potassium_mg: 512,
  },
  {
    name: "Cauliflower (raw)",
    serving_size: 107,
    serving_unit: "g",
    calories: 27,
    protein_g: 2,
    carbs_g: 5,
    fat_g: 0.3,
    fiber_g: 2,
    sugar_g: 2,
    sodium_mg: 32,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 52,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.4,
    calcium_mg: 24,
    potassium_mg: 320,
  },
  {
    name: "Cabbage (raw, shredded)",
    serving_size: 89,
    serving_unit: "g",
    calories: 22,
    protein_g: 1,
    carbs_g: 5,
    fat_g: 0.1,
    fiber_g: 2.2,
    sugar_g: 3,
    sodium_mg: 16,
    vitamin_a_mcg: 5,
    vitamin_c_mg: 33,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 36,
    potassium_mg: 151,
  },
  {
    name: "Kale (raw)",
    serving_size: 67,
    serving_unit: "g",
    calories: 33,
    protein_g: 3,
    carbs_g: 6,
    fat_g: 0.5,
    fiber_g: 2.4,
    sugar_g: 1.6,
    sodium_mg: 25,
    vitamin_a_mcg: 506,
    vitamin_c_mg: 80,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.1,
    calcium_mg: 90,
    potassium_mg: 329,
  },
  {
    name: "Lettuce (romaine, shredded)",
    serving_size: 85,
    serving_unit: "g",
    calories: 15,
    protein_g: 1,
    carbs_g: 3,
    fat_g: 0.3,
    fiber_g: 2,
    sugar_g: 1.2,
    sodium_mg: 7,
    vitamin_a_mcg: 409,
    vitamin_c_mg: 19,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.9,
    calcium_mg: 28,
    potassium_mg: 229,
  },
  {
    name: "Onion (medium)",
    serving_size: 1,
    serving_unit: "onion",
    calories: 44,
    protein_g: 1.2,
    carbs_g: 10,
    fat_g: 0.1,
    fiber_g: 1.9,
    sugar_g: 5,
    sodium_mg: 4,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 8,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 25,
    potassium_mg: 161,
  },
  {
    name: "Mushrooms (white, raw)",
    serving_size: 96,
    serving_unit: "g",
    calories: 21,
    protein_g: 3,
    carbs_g: 3,
    fat_g: 0.3,
    fiber_g: 1,
    sugar_g: 2,
    sodium_mg: 5,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 2,
    vitamin_d_mcg: 0.2,
    vitamin_b12_mcg: 0,
    iron_mg: 0.5,
    calcium_mg: 3,
    potassium_mg: 305,
  },
  {
    name: "Asparagus (cooked)",
    serving_size: 134,
    serving_unit: "g",
    calories: 27,
    protein_g: 3,
    carbs_g: 5,
    fat_g: 0.2,
    fiber_g: 2.8,
    sugar_g: 2.5,
    sodium_mg: 16,
    vitamin_a_mcg: 50,
    vitamin_c_mg: 7,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1,
    calcium_mg: 32,
    potassium_mg: 224,
  },
  {
    name: "Green beans (cooked)",
    serving_size: 125,
    serving_unit: "g",
    calories: 44,
    protein_g: 2,
    carbs_g: 10,
    fat_g: 0.3,
    fiber_g: 4,
    sugar_g: 2,
    sodium_mg: 1,
    vitamin_a_mcg: 35,
    vitamin_c_mg: 12,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 55,
    potassium_mg: 182,
  },
  {
    name: "Peas (green, cooked)",
    serving_size: 160,
    serving_unit: "g",
    calories: 134,
    protein_g: 9,
    carbs_g: 25,
    fat_g: 0.4,
    fiber_g: 8.8,
    sugar_g: 9,
    sodium_mg: 7,
    vitamin_a_mcg: 76,
    vitamin_c_mg: 22,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 2.5,
    calcium_mg: 43,
    potassium_mg: 434,
  },
  {
    name: "Sweetcorn (cooked)",
    serving_size: 165,
    serving_unit: "g",
    calories: 143,
    protein_g: 5,
    carbs_g: 31,
    fat_g: 2,
    fiber_g: 3.9,
    sugar_g: 6.8,
    sodium_mg: 1,
    vitamin_a_mcg: 10,
    vitamin_c_mg: 6,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 3,
    potassium_mg: 392,
  },
  {
    name: "Celery (stalk)",
    serving_size: 1,
    serving_unit: "stalk",
    calories: 6,
    protein_g: 0.3,
    carbs_g: 1.2,
    fat_g: 0.1,
    fiber_g: 0.6,
    sugar_g: 0.5,
    sodium_mg: 51,
    vitamin_a_mcg: 11,
    vitamin_c_mg: 1,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.1,
    calcium_mg: 16,
    potassium_mg: 104,
  },
  {
    name: "Aubergine (eggplant, cooked)",
    serving_size: 99,
    serving_unit: "g",
    calories: 35,
    protein_g: 0.8,
    carbs_g: 9,
    fat_g: 0.2,
    fiber_g: 2.5,
    sugar_g: 3,
    sodium_mg: 5,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 2,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.2,
    calcium_mg: 9,
    potassium_mg: 122,
  },
  {
    name: "Brussels sprouts (cooked)",
    serving_size: 156,
    serving_unit: "g",
    calories: 56,
    protein_g: 4,
    carbs_g: 11,
    fat_g: 0.8,
    fiber_g: 4.1,
    sugar_g: 2.7,
    sodium_mg: 16,
    vitamin_a_mcg: 60,
    vitamin_c_mg: 97,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.9,
    calcium_mg: 56,
    potassium_mg: 494,
  },
  {
    name: "Beetroot (cooked)",
    serving_size: 136,
    serving_unit: "g",
    calories: 60,
    protein_g: 2.2,
    carbs_g: 13,
    fat_g: 0.2,
    fiber_g: 3.8,
    sugar_g: 10,
    sodium_mg: 106,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 4,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.1,
    calcium_mg: 22,
    potassium_mg: 442,
  },
  {
    name: "Green pepper (medium)",
    serving_size: 1,
    serving_unit: "pepper",
    calories: 24,
    protein_g: 1,
    carbs_g: 6,
    fat_g: 0.2,
    fiber_g: 2,
    sugar_g: 3,
    sodium_mg: 4,
    vitamin_a_mcg: 18,
    vitamin_c_mg: 120,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.4,
    calcium_mg: 14,
    potassium_mg: 208,
  },
  // Legumes & nuts
  {
    name: "Lentils (cooked)",
    serving_size: 198,
    serving_unit: "g",
    calories: 230,
    protein_g: 18,
    carbs_g: 40,
    fat_g: 0.8,
    fiber_g: 16,
    sugar_g: 2,
    sodium_mg: 4,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 3,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 6.6,
    calcium_mg: 38,
    potassium_mg: 731,
  },
  {
    name: "Black beans (cooked)",
    serving_size: 172,
    serving_unit: "g",
    calories: 227,
    protein_g: 15,
    carbs_g: 41,
    fat_g: 0.9,
    fiber_g: 15,
    sugar_g: 0.6,
    sodium_mg: 2,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 3.6,
    calcium_mg: 46,
    potassium_mg: 611,
  },
  {
    name: "Peanut butter",
    serving_size: 32,
    serving_unit: "g",
    calories: 188,
    protein_g: 8,
    carbs_g: 6,
    fat_g: 16,
    fiber_g: 2,
    sugar_g: 3,
    sodium_mg: 136,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.6,
    calcium_mg: 17,
    potassium_mg: 189,
  },
  {
    name: "Walnuts",
    serving_size: 28,
    serving_unit: "g",
    calories: 185,
    protein_g: 4,
    carbs_g: 4,
    fat_g: 18,
    fiber_g: 2,
    sugar_g: 0.7,
    sodium_mg: 1,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.8,
    calcium_mg: 28,
    potassium_mg: 125,
  },
  {
    name: "Cashews",
    serving_size: 28,
    serving_unit: "g",
    calories: 157,
    protein_g: 5,
    carbs_g: 9,
    fat_g: 12,
    fiber_g: 0.9,
    sugar_g: 1.7,
    sodium_mg: 3,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.9,
    calcium_mg: 10,
    potassium_mg: 187,
  },
  {
    name: "Pistachios",
    serving_size: 28,
    serving_unit: "g",
    calories: 159,
    protein_g: 6,
    carbs_g: 8,
    fat_g: 13,
    fiber_g: 3,
    sugar_g: 2.2,
    sodium_mg: 0,
    vitamin_a_mcg: 6,
    vitamin_c_mg: 1,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.1,
    calcium_mg: 30,
    potassium_mg: 291,
  },
  {
    name: "Pecans",
    serving_size: 28,
    serving_unit: "g",
    calories: 196,
    protein_g: 3,
    carbs_g: 4,
    fat_g: 20,
    fiber_g: 2.7,
    sugar_g: 1.1,
    sodium_mg: 0,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.7,
    calcium_mg: 20,
    potassium_mg: 116,
  },
  {
    name: "Macadamia nuts",
    serving_size: 28,
    serving_unit: "g",
    calories: 204,
    protein_g: 2,
    carbs_g: 4,
    fat_g: 21,
    fiber_g: 2.4,
    sugar_g: 1.3,
    sodium_mg: 1,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1,
    calcium_mg: 24,
    potassium_mg: 104,
  },
  {
    name: "Hazelnuts",
    serving_size: 28,
    serving_unit: "g",
    calories: 178,
    protein_g: 4,
    carbs_g: 5,
    fat_g: 17,
    fiber_g: 2.8,
    sugar_g: 1.2,
    sodium_mg: 0,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 2,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.3,
    calcium_mg: 32,
    potassium_mg: 193,
  },
  {
    name: "Brazil nuts",
    serving_size: 28,
    serving_unit: "g",
    calories: 186,
    protein_g: 4,
    carbs_g: 3,
    fat_g: 19,
    fiber_g: 2.1,
    sugar_g: 0.7,
    sodium_mg: 1,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.7,
    calcium_mg: 45,
    potassium_mg: 187,
  },
  {
    name: "Pine nuts",
    serving_size: 28,
    serving_unit: "g",
    calories: 191,
    protein_g: 4,
    carbs_g: 4,
    fat_g: 19,
    fiber_g: 1,
    sugar_g: 1,
    sodium_mg: 0,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.6,
    calcium_mg: 4,
    potassium_mg: 169,
  },
  {
    name: "Mixed nuts (unsalted)",
    serving_size: 28,
    serving_unit: "g",
    calories: 172,
    protein_g: 5,
    carbs_g: 6,
    fat_g: 15,
    fiber_g: 2,
    sugar_g: 1.5,
    sodium_mg: 2,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1,
    calcium_mg: 30,
    potassium_mg: 180,
  },
  // Fats & extras
  {
    name: "Olive oil",
    serving_size: 14,
    serving_unit: "ml",
    calories: 119,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0,
    calcium_mg: 0,
    potassium_mg: 0,
  },
  {
    name: "Butter",
    serving_size: 14,
    serving_unit: "g",
    calories: 102,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 12,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 91,
    vitamin_a_mcg: 97,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0.1,
    vitamin_b12_mcg: 0,
    iron_mg: 0,
    calcium_mg: 3,
    potassium_mg: 3,
  },
  {
    name: "Dark chocolate (70%)",
    serving_size: 28,
    serving_unit: "g",
    calories: 170,
    protein_g: 2,
    carbs_g: 13,
    fat_g: 12,
    fiber_g: 3,
    sugar_g: 7,
    sodium_mg: 5,
    vitamin_a_mcg: 1,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 3.3,
    calcium_mg: 20,
    potassium_mg: 203,
  },
  {
    name: "Honey",
    serving_size: 21,
    serving_unit: "g",
    calories: 64,
    protein_g: 0.1,
    carbs_g: 17,
    fat_g: 0,
    fiber_g: 0,
    sugar_g: 17,
    sodium_mg: 1,
    vitamin_a_mcg: 0,
    vitamin_c_mg: 0,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 0.1,
    calcium_mg: 1,
    potassium_mg: 11,
  },
  {
    name: "Hummus",
    serving_size: 60,
    serving_unit: "g",
    calories: 100,
    protein_g: 3,
    carbs_g: 9,
    fat_g: 6,
    fiber_g: 3,
    sugar_g: 0.5,
    sodium_mg: 170,
    vitamin_a_mcg: 2,
    vitamin_c_mg: 2,
    vitamin_d_mcg: 0,
    vitamin_b12_mcg: 0,
    iron_mg: 1.2,
    calcium_mg: 30,
    potassium_mg: 120,
  },
];

function dedupeFoods(foods: SeedFood[]): SeedFood[] {
  const seen = new Set<string>();
  const out: SeedFood[] = [];
  for (const food of foods) {
    const key = food.name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(food);
  }
  return out;
}

export const SEED_FOODS: SeedFood[] = dedupeFoods([
  ...BASE_SEED_FOODS,
  ...STAPLE_SEED_FOODS,
  ...CATALOG_SEED_FOODS,
  ...BULGARIAN_SEED_FOODS,
]);

export function foodSummary(food: Pick<Food, "name" | "calories" | "protein_g" | "serving_size" | "serving_unit">) {
  return `${food.calories} kcal · ${food.protein_g}g protein per ${food.serving_size} ${food.serving_unit}`;
}
